# Generated by Django 2.1.1 on 2018-09-10 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksrentalapp', '0003_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
    atomic = False
