# Generated by Django 2.1.1 on 2018-09-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksrentalapp', '0005_auto_20180910_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
